[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "glabels"
description = "Simple wrapper for glabels-3-batch and glabels-batch-qt"
version = "0.1.0"
readme = "README.md"
requires-python = ">=3.6"
